name: CodeGuardian libclang debug

on:
  pull_request:
    paths:
      - '**/*.c'
      - 'agent/**'

jobs:
  debug-libclang:
    runs-on: ubuntu-latest
    env:
      CODEGUARDIAN_DEBUG: '1'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y clang libclang-dev
      - name: Install pip deps
        run: python -m pip install -r requirements.txt
      - name: Run tests
        run: python -m pytest -q
  windows-debug:
    runs-on: windows-latest
    needs: debug-libclang
    env:
      CODEGUARDIAN_DEBUG: '1'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install LLVM via Chocolatey
        shell: powershell
        run: |
          choco install -y llvm
      - name: Find libclang DLL
        shell: powershell
        run: |
          python scripts\find_libclang_windows.py > libclang_path.txt || exit 0
      - name: Dump libclang path
        shell: powershell
        run: |
          if (Test-Path libclang_path.txt) { Get-Content libclang_path.txt | Write-Output } else { Write-Output 'no-libclang-found' }
      - name: Set PATH for libclang if found
        shell: powershell
        run: |
          if (Test-Path libclang_path.txt) {
            $p = Get-Content libclang_path.txt | Select-Object -First 1
            $dir = Split-Path $p
            Write-Output "Adding $dir to PATH"
            # use the Actions env file mechanism to add to PATH
            "$dir" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          } else {
            Write-Output "libclang DLL not found; continuing without explicit PATH change"
          }
      - name: Install pip deps
        run: python -m pip install -r requirements.txt
      - name: Run tests on Windows
        run: python -m pytest -q --maxfail=1 --disable-warnings -k "not slow"
      - name: Upload debug logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: codeguardian-debug-logs
          path: |
            .pytest_cache
            pytest-report.xml
